---
version: "3"
services:
  server:
    build:
      context: ./server
      dockerfile: ./Dockerfile
    volumes:
      - ./server:/app
    ports:
      - "5000:5000"
    env_file:
      - ./config/db.env
  listener:
    build:
      context: ./server
      dockerfile: ./Dockerfile
    volumes:
      - ./server:/app
    command: ["node", "./src/listener.js"]
    env_file:
      - ./config/db.env
  blockchain:
    image: trufflesuite/ganache-cli:latest
    ports:
      - "8545:8545"
    volumes:
      - blockchaindata:/ganache_data
    command:
      - "--deterministic"
      - "--mnemonic"
      - "mind gesture pizza when gloom spoil invest alpha common switch apple autumn"
      - "--db=/ganache_data"
      - "--networkId"
      - "5777"
  db:
    image: postgis/postgis:latest
    ports:
      - "5432:5432"
    volumes:
      - worldstate:/var/lib/postgresql/data
      # - ./db_init:/docker-entrypoint-initdb.d
    env_file:
      - ./config/db.env
volumes:
  blockchaindata:
  worldstate:
